language:
  - python

service:
  - docker

branches:
  only:
  - master

install:       
  - pip install ansible

before_script:
  - echo $PRIVATE_KEY > key.pem

script:
  - docker build -t alvarobacelar/app-admin .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alvarobacelar/app-admin-test
  - cd ansible && ansible-playbook -i inventories/prd deploy-app.yml --private-key key.pem -s
