language:
  - python

service:
  - docker

branches:
  only:
  - master

install:       
  - pip install ansible

script:
  - docker build -t alvarobacelar/app-admin-test .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alvarobacelar/app-admin-test
  - echo $PRIVATE_KEY > /tmp/key.pem && chmod 600 /tmp/key.pem
  - cd ansible && ansible-playbook -i inventories/prd deploy-app.yml --private-key /tmp/key.pem -s
